Task 13.5
AdamPawlinski/task-13.5 pull request #1
Opened 2018-04-06 05:10 UTC by AdamPawlinski

Task 13.5 finished. Please accept merging.

2018-04-15 04:19 UTC, AdamPawlinski commented
Fixed. Please accept final work.

2018-04-15 08:52 UTC, matwjablonski requested changes

2018-04-15 08:52 UTC, matwjablonski commented on index.js
> +  if (input === null) {
use negation ;) `if (!input)`

2018-04-15 08:52 UTC, matwjablonski commented on index.js
> +    return
after return add `;`

2018-04-16 03:59 UTC, AdamPawlinski commented
changes made

2018-04-16 05:35 UTC, matwjablonski approved these changes

2018-09-14 03:38 UTC, merged